[package]
name = "aoc_2024_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.2"
itertools = "0.13.0"
miette = "7.4.0"
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
pathfinding = "4.12.0"
regex = "1.11.1"
